import { useMemo, useState } from "react";
import { BadgeCheck, Check, ChevronDown, MapPin, MessageCircle, PackageCheck, Plus, Search, SlidersHorizontal, Store, X } from "lucide-react";
import { Link } from "wouter";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

const listings = [
  { id: "produce-basket", title: "Fresh Farm Produce Basket", seller: "Mama Njeri Fresh Foods", category: "Food & Grocery", county: "Kiambu", price: "KSh 1,500", image: "/images/hero-agribusiness.png", unit: "per basket", availability: "Ready this week", summary: "Seasonal vegetables, fruit and pantry staples packed for homes and small restaurants." },
  { id: "mitumba-bales", title: "Quality Mitumba Bales", seller: "Pamoja Fashion Traders", category: "Clothing & Fashion", county: "Nairobi", price: "KSh 18,000", image: "/images/hero-textile.png", unit: "per bale", availability: "Wholesale", summary: "Curated bale options for resellers, boutiques and market traders." },
  { id: "solar-kit", title: "Solar Phone Charging Kit", seller: "Mwangaza Digital Shop", category: "Electronics", county: "Kisumu", price: "KSh 4,500", image: "/images/hero-tech.png", unit: "per kit", availability: "In stock", summary: "A practical charging setup for shops, agents and off-grid customers." },
  { id: "beaded-baskets", title: "Handmade Beaded Baskets", seller: "Soko Creative Collective", category: "Crafts & Gifts", county: "Kajiado", price: "From KSh 800", image: "/images/hero-artisanal.png", unit: "per piece", availability: "Made to order", summary: "Hand-finished baskets for gifting, interiors, retail and corporate orders." },
  { id: "gas-accessories", title: "Wholesale Cooking Gas Accessories", seller: "Safe Gas Suppliers", category: "Fuel & Energy", county: "Mombasa", price: "KSh 2,200", image: "/images/hero-manufacturing.png", unit: "from", availability: "Wholesale", summary: "Reliable accessories for households, retailers and hospitality businesses." },
  { id: "cleaning-team", title: "Office & Home Cleaning Service", seller: "Jirani Clean Team", category: "Services", county: "Nakuru", price: "Request quote", image: "/images/hero-retail.png", unit: "per visit", availability: "Booking open", summary: "Scheduled cleaning support for offices, homes, shops and shared spaces." },
];

const trustOptions = ["All member profiles", "Registered members"];

export default function Marketplace() {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("All");
  const [county, setCounty] = useState("All counties");
  const [trust, setTrust] = useState(trustOptions[0]);
  const [filtersOpen, setFiltersOpen] = useState(false);
  const categories = ["All", ...Array.from(new Set(listings.map((item) => item.category)))];
  const counties = ["All counties", ...Array.from(new Set(listings.map((item) => item.county)))];
  const filtered = useMemo(() => listings.filter((item) => {
    const matchesQuery = `${item.title} ${item.seller} ${item.county} ${item.category}`.toLowerCase().includes(query.toLowerCase());
    return matchesQuery && (category === "All" || item.category === category) && (county === "All counties" || item.county === county) && (trust === "All member profiles" || trust === "Registered members");
  }), [query, category, county, trust]);

  const clearFilters = () => { setQuery(""); setCategory("All"); setCounty("All counties"); setTrust(trustOptions[0]); };

  return <div className="min-h-[100dvh]">
    <section className="bg-foreground text-background"><div className="app-shell py-16 md:py-24"><div className="max-w-4xl"><Badge className="mb-5 border-0 bg-accent text-accent-foreground" data-testid="badge-marketplace">BNAK MARKETPLACE</Badge><h1 className="text-balance text-5xl font-bold leading-[.95] md:text-7xl">Trade with more context.</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-background/70">A focused marketplace for products and services from BNAK member businesses. Browse the starter listings, check the seller context, then enquire directly.</p></div><div className="mt-9 flex flex-wrap gap-4 text-sm font-semibold text-background/65"><span className="flex items-center gap-2"><BadgeCheck className="h-4 w-4 text-accent" /> Registered-member profiles</span><span className="flex items-center gap-2"><MessageCircle className="h-4 w-4 text-accent" /> WhatsApp enquiries</span><span className="flex items-center gap-2"><Store className="h-4 w-4 text-accent" /> Kenya-wide discovery</span></div></div></section>
    <section className="app-shell py-10 md:py-14">
      <div className="mb-8 flex flex-col gap-4 rounded-3xl border border-border bg-card p-4 shadow-sm md:p-5"><div className="flex flex-col gap-3 lg:flex-row"><label className="relative flex-1"><span className="sr-only">Search marketplace</span><Search className="absolute left-4 top-3.5 h-4 w-4 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search products, services, sellers or counties" className="h-11 border-border bg-background pl-11" data-testid="input-marketplace-search" /></label><Button type="button" variant="outline" className="justify-between lg:hidden" onClick={() => setFiltersOpen((current) => !current)} data-testid="button-marketplace-filters"><span className="flex items-center gap-2"><SlidersHorizontal className="h-4 w-4" /> Filters</span>{filtersOpen ? <X className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}</Button><div className={`${filtersOpen ? "grid" : "hidden"} gap-3 sm:grid-cols-2 lg:flex lg:flex-1`}><Select value={category} onValueChange={setCategory}><SelectTrigger className="h-11 bg-background lg:w-44" data-testid="select-marketplace-category"><SelectValue placeholder="Category" /></SelectTrigger><SelectContent>{categories.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select><Select value={county} onValueChange={setCounty}><SelectTrigger className="h-11 bg-background lg:w-44" data-testid="select-marketplace-county"><SelectValue placeholder="County" /></SelectTrigger><SelectContent>{counties.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select><Select value={trust} onValueChange={setTrust}><SelectTrigger className="h-11 bg-background lg:w-48" data-testid="select-marketplace-trust"><SelectValue placeholder="Member status" /></SelectTrigger><SelectContent>{trustOptions.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div><Button asChild className="h-11 whitespace-nowrap" data-testid="button-marketplace-register"><Link href="/membership"><Plus className="mr-2 h-4 w-4" /> Register to list</Link></Button></div><div className="flex flex-wrap items-center justify-between gap-3 text-sm"><p className="text-muted-foreground" data-testid="text-marketplace-result-count">{filtered.length} starter {filtered.length === 1 ? "listing" : "listings"} shown</p><button type="button" onClick={clearFilters} className="font-bold text-primary hover:underline" data-testid="button-marketplace-clear">Clear filters</button></div></div>
      <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-primary">Member listings</p><h2 className="mt-2 text-2xl font-bold md:text-3xl">Find your next supplier or customer.</h2></div><p className="max-w-sm text-sm leading-relaxed text-muted-foreground">Trust labels show the profile context available for these starter listings. Confirm details directly with the seller.</p></div>
      <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">
        {filtered.map((item) => <Card key={item.id} className="group flex h-full flex-col overflow-hidden border-card-border bg-card transition-transform hover:-translate-y-1 hover:shadow-lg" data-testid={`card-listing-${item.id}`}><div className="relative h-52 overflow-hidden bg-muted"><img src={item.image} alt={item.title} className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-105" /><div className="absolute inset-x-0 top-0 flex items-start justify-between p-3"><Badge className="border-0 bg-background/90 text-foreground">{item.category}</Badge><Badge className="border-0 bg-secondary text-secondary-foreground"><Check className="mr-1 h-3 w-3" /> Registered</Badge></div></div><CardHeader className="pb-3"><div className="flex items-start justify-between gap-3"><CardTitle className="text-xl leading-tight">{item.title}</CardTitle><span className="whitespace-nowrap text-right text-sm font-bold text-primary">{item.price}<span className="block text-[10px] font-medium text-muted-foreground">{item.unit}</span></span></div><p className="pt-2 text-sm leading-relaxed text-muted-foreground">{item.summary}</p></CardHeader><CardContent className="flex-1 space-y-3"><div className="flex items-center justify-between gap-3 rounded-xl bg-secondary/5 p-3 text-sm"><span className="flex items-center gap-2 font-bold"><BadgeCheck className="h-4 w-4 text-secondary" /> {item.seller}</span><span className="text-xs font-semibold text-secondary">BNAK member</span></div><div className="flex items-center justify-between text-sm text-muted-foreground"><span className="flex items-center gap-2"><MapPin className="h-4 w-4 text-primary" /> {item.county}, Kenya</span><span className="flex items-center gap-1.5"><PackageCheck className="h-4 w-4 text-secondary" /> {item.availability}</span></div></CardContent><CardFooter><Button className="w-full" variant="outline" asChild data-testid={`button-enquire-${item.id}`}><a href={`https://wa.me/254711422163?text=${encodeURIComponent(`Hello BNAK, I am interested in ${item.title} from ${item.seller}.`)}`} target="_blank" rel="noreferrer"><MessageCircle className="mr-2 h-4 w-4" /> Enquire on WhatsApp</a></Button></CardFooter></Card>)}
      </div>
      {filtered.length === 0 && <div className="rounded-3xl border border-dashed border-border bg-muted/30 px-6 py-20 text-center" data-testid="empty-marketplace"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-primary/10 text-primary"><Search className="h-6 w-6" /></div><h3 className="mt-5 text-xl font-bold">No starter listings match those filters.</h3><p className="mx-auto mt-2 max-w-md text-sm leading-relaxed text-muted-foreground">Try a broader search, or register your business to be considered for a future BNAK marketplace listing.</p><div className="mt-6 flex justify-center gap-3"><Button variant="outline" onClick={clearFilters} data-testid="button-marketplace-empty-clear">Clear filters</Button><Button asChild data-testid="button-marketplace-empty-register"><Link href="/membership">Register your business</Link></Button></div></div>}
    </section>
  </div>;
}